export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "To do list",
  headLine: "You can do it! better than yesterday",
  description: "Make your today plan",
  buttonLabel: "Get Started",
  imgStart: false,
  img: require("../../images/todo.png"),
  alt: "planimg",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "second",
  headLine: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  description: "get your plan data",
  buttonLabel: "Lean More",
  imgStart: true,
  img: require("../../images/planimg.jpg"),
  alt: "planimg",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjTree = {
  id: "service",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Last",
  headLine: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  description: "Make your today plan",
  buttonLabel: "Get Started",
  imgStart: false,
  img: require("../../images/planimg.jpg"),
  alt: "planimg",
  dark: true,
  primary: true,
  darkText: false,
};
